name: Gerar Executavel Offline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixando seu Código
        uses: actions/checkout@v4

      - name: Baixando Motor NWJS
        run: |
          curl -L https://dl.nwjs.io/v0.82.0/nwjs-v0.82.0-win-x64.zip -o nwjs.zip
          Expand-Archive -Path nwjs.zip -DestinationPath .
          Move-Item -Path nwjs-v0.82.0-win-x64 -Destination app_pasta

      - name: Juntar Arquivos
        run: |
          # Este comando copia tudo o que voce tem no GitHub para dentro da pasta do app
          Get-ChildItem -Exclude "nwjs.zip", "app_pasta", ".github", ".git" | Copy-Item -Destination app_pasta -Recurse

      - name: Finalizar Download
        uses: actions/upload-artifact@v4
        with:
          name: Sistema_Gestao_Offline
          path: app_pasta/
