name: Gerar Executavel Offline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixando seu Código
        uses: actions/checkout@v4

      - name: Baixando o Motor do App (NW.js)
        run: |
          curl -L https://dl.nwjs.io/v0.82.0/nwjs-v0.82.0-win-x64.zip -o nwjs.zip
          Expand-Archive -Path nwjs.zip -DestinationPath .
          Move-Item -Path nwjs-v0.82.0-win-x64 -Destination app_pasta

      - name: Preparando os Arquivos
        run: |
          # Copia TUDO o que for arquivo do seu projeto para a pasta do app
          # Isso evita erros de nomes de arquivos individuais
          Copy-Item -Path * -Destination app_pasta -Exclude "nwjs.zip","app_pasta" -Recurse -ErrorAction Ignore

      - name: Disponibilizar para Download
        uses: actions/upload-artifact@v4
        with:
          name: Gestao_Offline_Pronta
          path: app_pasta/
