name: Gerar Executavel Offline

on:
  workflow_dispatch: # Para você apertar o botão de Play

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixando seu Código
        uses: actions/checkout@v4

      - name: Baixando o Motor do App (NW.js)
        run: |
          curl -L https://dl.nwjs.io/v0.82.0/nwjs-v0.82.0-win-x64.zip -o nwjs.zip
          expand-archive -path nwjs.zip -destinationpath .
          mv nwjs-v0.82.0-win-x64 app_pasta

      - name: Preparando os Arquivos
        run: |
          # Move seus arquivos para dentro da pasta do app
          cp index.html app_pasta/
          cp gestao.js app_pasta/
          cp estilo.css app_pasta/
          cp manifest.json app_pasta/
          cp ícone.png app_pasta/

      - name: Criando o Pacote Final
        run: |
          cd app_pasta
          # Transforma a pasta em um executavel compacto
          copy /b nw.exe+index.html gestao_offline.exe

      - name: Disponibilizar para Download
        uses: actions/upload-artifact@v4
        with:
          name: Gestao_Offline_Pronta
          path: app_pasta/
